import os
import urllib.request
import json
import logging
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

logger = logging.getLogger("uvicorn")
router = APIRouter()

class GoogleLoginRequest(BaseModel):
    token: str

def verify_google_token(token: str) -> dict:
    url = f"https://oauth2.googleapis.com/tokeninfo?id_token={token}"
    try:
        req = urllib.request.Request(
            url,
            headers={"User-Agent": "FastAPI Google Auth Client"}
        )
        with urllib.request.urlopen(req, timeout=10) as response:
            data = json.loads(response.read().decode())
            if "error" in data:
                raise ValueError(data.get("error_description", "Invalid token"))
            return data
    except Exception as e:
        logger.error(f"Google token validation failed: {str(e)}")
        raise ValueError(f"Token validation failed: {str(e)}")

@router.post("/auth/google")
async def google_auth(request: GoogleLoginRequest):
    """
    Receives the Google OAuth2 ID Token (JWT) from frontend,
    validates it cryptographically via Google's secure tokeninfo service,
    and returns user profile metadata.
    """
    token = request.token
    if not token:
        raise HTTPException(status_code=400, detail="Token is missing.")
        
    try:
        idinfo = verify_google_token(token)
        
        # Verify audience matches client ID if set
        google_client_id = os.getenv("GOOGLE_CLIENT_ID") or os.getenv("VITE_GOOGLE_CLIENT_ID")
        if google_client_id:
            aud = idinfo.get("aud")
            if aud != google_client_id:
                logger.warning(f"Audience mismatch: expected {google_client_id}, got {aud}")
                # Enforce secure audience check
                raise ValueError("Audience mismatch. Token not generated by authorized client.")
                
        # Extract profile info
        email = idinfo.get("email")
        name = idinfo.get("name", "Google User")
        picture = idinfo.get("picture")
        
        if not email:
            raise HTTPException(status_code=400, detail="Email not provided in Google ID token.")
            
        logger.info(f"Successfully authenticated Google user: {email} ({name})")
        
        return {
            "name": name,
            "email": email,
            "avatarUrl": picture
        }
        
    except ValueError as e:
        raise HTTPException(status_code=401, detail=str(e))
    except Exception as e:
        logger.exception("Unexpected error during Google authentication")
        raise HTTPException(status_code=500, detail="Internal server authentication error.")
